name: Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dify repository
        uses: actions/checkout@v2
        with:
          repository: langgenius/dify

      - name: Display directory structure
        run: ls

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and start containers
        run: |
          cd docker
          docker-compose up -d

      - name: Check container status
        run: docker-compose ps
        
      - name: Set up ngrok and expose port
        run: |
          docker run -d --name ngrok -e NGROK_AUTHTOKEN=2fUArZstmOUGKwgdV7NSN4PCMgt_YGSDYKR1oydqx5zLaEF2 -p 4040:4040 ngrok/ngrok http http://localhost:80
