name: Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dify repository
        uses: actions/checkout@v2
        with:
          repository: langgenius/dify

      - name: Display directory structure
        run: ls

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and start containers
        run: |
          cd docker
          docker-compose up -d

      - name: Check container status
        run: |
          cd docker
          docker-compose ps
        
      - name: Download and install ngrok
        run: |
           curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update && sudo apt install ngrok
          
      - name: Set up ngrok
        run: ngrok config add-authtoken ${{ secrets.NGROK_AUTHTOKEN }}

      - name: Start ngrok tunnel
        run: ngrok http --domain=flea-great-joey.ngrok-free.app 80
        timeout-minutes: 1000000000000000000000000000000000000000000000000000000000000000
