name: Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dify repository
        uses: actions/checkout@v2
        with:
          repository: langgenius/dify

      - name: Display directory structure
        run: ls

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and start containers
        run: |
          cd docker
          docker-compose up -d

      - name: Check container status
        run: |
          cd docker
          docker-compose ps
        
      - name: Set up ngrok
        run: |
          docker pull ngrok/ngrok
      
      - name: Build and start ngrok
        run: |
          docker run -d --name ngrok -e NGROK_AUTHTOKEN=2gPtkkirCaj7o63UqKPoEK6VuDr_3anDih2edcmfLiyRN2vtm -p 4040:4040 ngrok/ngrok http http://localhost:install
