name: Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dify repository
        uses: actions/checkout@v2
        with:
          repository: langgenius/dify

      - name: Display directory structure
        run: ls

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and start containers
        run: |
          cd docker
          docker-compose up -d

      - name: Check container status
        run: |
          cd docker
          docker-compose ps
        
      - name: Set up ngrok and expose port
        run: |
          docker pull ngrok/ngrok
          docker run --net=host -it -e NGROK_AUTHTOKEN=2RmkREVcca3UpvPU03gruAcqWhF_4YcND1Pdjt8nG1r2Gya5i ngrok/ngrok:latest http --domain=flea-great-joey.ngrok-free.app 80
